// Generated by CoffeeScript 1.12.7
(function() {
  $(function() {
    var base_room, base_rooms, i, imgUrl, initialRoomId, initialRoomImg, initialRoomName, len, load_start, members_json, roomId, roomName, rooms_info, targetRoomId, time_now;
    $("#hotpoor_shares_qrcode_weixin_area").remove();
    $("#hotpoor_shares").css({
      "position": "relative",
      "paddingBottom": "0px",
      "height": "100%"
    });
    $("#hotpoor_shares").append("<style>\n    .comments_area{\n        width:100%;\n        height:calc(100% - 44px);\n        overflow-y: auto;\n    }\n    .comments_area_tools{\n        width:100%;\n        height:44px;\n        background-color:#f2f2f2;\n        border-top:1px solid #d4d4d4;\n        position:relative;\n    }\n    .comment_content{\n        width: calc(100% - 82px);\n        border-radius: 4px;\n        border: 1px solid #c3c3c3;\n        resize: none;\n        position: absolute;\n        left: 4px;\n        top: 3px;\n        font-size: 14px;\n        padding: 4px;\n        height: 26px;\n    }\n    .comment_submit{\n        width: 60px;\n        height: 30px;\n        font-size: 15px;\n        color: #999999;\n        border-radius: 7px;\n        border: 1px solid #c3c3c3;\n        background-color: #f2f2f2;\n        position: absolute;\n        right: 4px;\n        top: 5px;\n        padding-left: 2px;\n        padding-right: 2px;\n    }\n</style>");
    $("#hotpoor_shares").append("<div class=\"comments_area\">\n</div>\n<div class=\"comments_area_tools\">\n    <textarea class=\"comment_content\"></textarea><button class=\"comment_submit\">发送</button>\n</div>");
    $("#hotpoor_shares").on("touchstart", ".comments_area", function(e) {
      var el_now, scrollTop;
      el_now = this;
      scrollTop = el_now.scrollTop;
      if (scrollTop === 0) {
        el_now.scrollTop = 1;
      }
      if (el_now.scrollTop + el_now.offsetHeight === el_now.scrollHeight) {
        return el_now.scrollTop = parseInt(el_now.scrollHeight) - parseInt(el_now.offsetHeight) - 1;
      }
    });
    targetRoomId = null;
    initialRoomId = "0cd8429c1da249b6935d7eef72d7fc0b";
    initialRoomImg = "http://image.hotpoor.org/2dd2c53e7c654c66b398e574848d4c34_08aed20957caca43b0df23442de17f6f?imageView2/2/w/200";
    initialRoomName = "夏力维和他的朋友们";
    base_rooms = [[initialRoomId, initialRoomImg, initialRoomName]];
    rooms_info = {};
    for (i = 0, len = base_rooms.length; i < len; i++) {
      base_room = base_rooms[i];
      roomId = base_room[0];
      imgUrl = base_room[1];
      roomName = base_room[2];
      time_now = (new Date()).getTime() / 1000;
      rooms_info[roomId] = {
        "imgUrl": imgUrl,
        "roomName": roomName,
        "createtime": time_now,
        "finishtime": 0,
        "room_time_flag": time_now,
        "createuser": "",
        "finishuser": "",
        "createcommentsequence": "",
        "finishcommentsequence": "",
        "latestComment": "",
        "last_comment_id": "",
        "roomNewMsgCount": 0
      };
    }
    members_json = {};
    load_start = function() {
      $(".comments_area").empty();
      return $.ajax({
        url: 'http://www.hotpoor.org/api/comment/load',
        type: 'POST',
        dataType: 'json',
        data: {
          app: 'bangfer',
          aim_id: roomId,
          comment_id: rooms_info[roomId].last_comment_id
        },
        success: function(data) {
          var _msg, comment, comments, j, len1, members_json_new, members_json_now, results;
          console.log(data);
          if (data.info === "ok") {
            rooms_info[roomId].last_comment_id = data.last_comment_id;
            members_json_now = members_json;
            members_json_new = data.members;
            members_json = $.extend({}, members_json_now, members_json_new);
            comments = data.comments;
            results = [];
            for (j = 0, len1 = comments.length; j < len1; j++) {
              comment = comments[j];
              _msg = [
                comment[3], {
                  "content": comment[4],
                  "nickname": members_json[comment[1]].nickname,
                  "headimgurl": members_json[comment[1]].headimgurl,
                  "time": comment[2],
                  "user_id": comment[1],
                  "tel": members_json[comment[1]].tel,
                  "plus": comment[5],
                  "sequence": comment[0],
                  "comment_id": data.comment_id
                }, roomId
              ];
              results.push(console.log(_msg));
            }
            return results;
          }
        },
        error: function(error) {
          return console.log(error);
        }
      });
    };
    return load_start();
  });

}).call(this);
