// Generated by CoffeeScript 1.12.7
(function() {
  $()(function() {
    $("#hotpoor_shares_qrcode_weixin_area").remove();
    $("#hotpoor_shares").css({
      "position": "relative",
      "paddingBottom": "0px",
      "height": "100%"
    });
    $("#hotpoor_shares").append("<style>\n    .comments_area{\n\n    }\n    .comments_area_tools{\n        position:fixed;\n        bottom:0px;\n        width:100%;\n        height:40px;\n        background-color:#f2f2f2;\n        border-top:1px solid #999;\n    }\n</style>");
    return $("#hotpoor_shares").append("<div class=\"comments_area\"></div>\n<div class=\"comments_area_tools\">\n    <textarea></textarea><button>发送<button>\n</div>");
  });

}).call(this);
